# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'ISS_MapCheck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for ISS_MapCheck
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod 'GoogleMaps'
  pod 'SwiftKeychainWrapper'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.2'

end
